import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
import { load } from "npm:cheerio@1.0.0";
const TZ="Europe/Ljubljana", URL="https://slg-ce.si/domov/spored/tedenski.html";
const clean=(v:any)=>String(v??"").replace(/\s+/g," ").trim();
function off(ts:number){const p=new Intl.DateTimeFormat("en-CA",{timeZone:TZ,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23"}).formatToParts(new Date(ts));const v:any=Object.fromEntries(p.map(x=>[x.type,x.value]));return Date.UTC(+v.year,+v.month-1,+v.day,+v.hour,+v.minute,+v.second)-ts}
function iso(y:number,m:number,d:number,h:number,min:number){const w=Date.UTC(y,m-1,d,h,min);let u=w-off(w);u=w-off(u);return new Date(u).toISOString()}
function day(v:string){const p=new Intl.DateTimeFormat("en-CA",{timeZone:TZ,year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date(v));const x:any=Object.fromEntries(p.map(z=>[z.type,z.value]));return `${x.year}-${x.month}-${x.day}`}
function norm(v:string){return v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9čšž]+/gi," ").replace(/\s+/g," ").trim()}
function sim(a:string,b:string){const x=norm(a),y=norm(b);if(x===y)return 1;if((x.includes(y)||y.includes(x))&&Math.min(x.length,y.length)>6)return .94;const A=new Set(x.split(" ")),B=new Set(y.split(" ")),i=[...A].filter(q=>B.has(q)).length,u=new Set([...A,...B]).size;return u?i/u:0}
Deno.serve(async(req)=>{if(req.method!=="POST")return new Response("Method not allowed",{status:405});const sb=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);const {data:s,error:se}=await sb.from("sources").select("id").eq("key","slg-celje").single();if(se||!s)return Response.json({ok:false,error:se?.message||"source missing"},{status:500});const r=await fetch(URL,{headers:{"user-agent":"Mozilla/5.0 (compatible; VCeljuSeNicNeDogaja/1.0)"}});if(!r.ok)return Response.json({ok:false,error:`HTTP ${r.status}`},{status:502});const $=load(await r.text()),text=clean($("body").text()),now=new Date().toISOString();const mm=text.match(/(JANUAR|FEBRUAR|MAREC|APRIL|MAJ|JUNIJ|JULIJ|AVGUST|SEPTEMBER|OKTOBER|NOVEMBER|DECEMBER)\s+(20\d{2})/i);if(!mm)return Response.json({ok:false,error:"month/year missing"},{status:502});const months:any={januar:1,februar:2,marec:3,april:4,maj:5,junij:6,julij:7,avgust:8,september:9,oktober:10,november:11,december:12},month=months[mm[1].toLowerCase()],year=+mm[2];const rows:any[]=[];const re=/(\d{1,2})\s+(?:ponedeljek|torek|sreda|četrtek|petek|sobota|nedelja)\s+(\d{1,2}):(\d{2})\s+(.{2,100}?)\s+([A-ZČŠŽ0-9][A-ZČŠŽ0-9 .,!?'()\-–:+\/]{3,120}?)(?=\s+(?:Premiera|izven|abonma|zaključena|RAZPRODANO|spletni nakup|\d{1,2}\s+(?:ponedeljek|torek|sreda|četrtek|petek|sobota|nedelja)|← nazaj|Slovensko ljudsko))/g;let m;while((m=re.exec(text))){const d=+m[1],h=+m[2],mi=+m[3],author=clean(m[4]),title=clean(m[5]);if(!title||/SLG CELJE NA GOSTOVANJU|PREDSTAVE V SLG/i.test(title))continue;const start=iso(year,month,d,h,mi);if(Date.parse(start)<Date.now()-86400000)continue;rows.push({source_id:s.id,source_event_id:`${year}-${month}-${d}-${h}-${mi}-${norm(title).slice(0,60)}`,title,slug:`slg-${year}-${month}-${d}-${h}-${mi}-${norm(title).replace(/ /g,"-").slice(0,70)}`,start_at:start,end_at:null,all_day:false,venue:"Slovensko ljudsko gledališče Celje",address:"Gledališki trg 5, 3000 Celje",city:"Celje",category:"Predstave",event_type:"single",is_free:null,price_text:null,description:author?`${author} — ${title}`:null,image_url:null,source_url:URL,status:"published",location_status:"in_area",duplicate_of:null,dedupe_confidence:null,dedupe_reason:null,raw:{direct_source:"slg-celje",author},last_seen_at:now,updated_at:now})}
if(!rows.length){await sb.from("sources").update({last_synced_at:now,updated_at:now}).eq("id",s.id);return Response.json({ok:true,month,year,imported:0,deduped:0,reason:"no_future_performances"});}
const {data:imp,error:ue}=await sb.from("events").upsert(rows,{onConflict:"source_id,source_event_id"}).select("id,title,start_at,venue");if(ue)return Response.json({ok:false,error:ue.message},{status:500});const {data:ds}=await sb.from("sources").select("id").like("import_method","direct_%"),direct=new Set((ds||[]).map((x:any)=>x.id));let deduped=0;for(const e of imp||[]){const lo=new Date(Date.parse(e.start_at)-3600000*18).toISOString(),hi=new Date(Date.parse(e.start_at)+3600000*18).toISOString();const {data:c}=await sb.from("events").select("id,title,start_at,venue,source_id,duplicate_of").neq("source_id",s.id).gte("start_at",lo).lte("start_at",hi).eq("status","published");for(const q of c||[]){if(direct.has(q.source_id)||q.duplicate_of)continue;const ts=sim(e.title,q.title);if(day(e.start_at)!==day(q.start_at)||ts<.78)continue;await sb.from("events").update({duplicate_of:e.id,dedupe_confidence:ts,dedupe_reason:`direct:title:${ts.toFixed(2)}`,updated_at:now}).eq("id",q.id);deduped++}}await sb.from("sources").update({last_synced_at:now,updated_at:now}).eq("id",s.id);return Response.json({ok:true,month,year,imported:rows.length,deduped,events:rows.map(x=>({title:x.title,start_at:x.start_at}))})});